blank_issues_enabled: false
contact_links:
  - name: HTG Version Control Procedure ğŸ”
    url: https://www.dropbox.com/home/888-BMS/TEC/PRO%20-%20Procedure
  - name: HTG Coding Standard ğŸ”
    url: https://www.dropbox.com/home/888-BMS/TEC/STD%20-%20Standard

